# Generated by Django 4.2 on 2024-05-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landelayo', '0002_alter_event_content_type_alter_event_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
